### ISSUE TITLE
Hide unrelated replies from home timeline

### ISSUE THREAD

**Issue by kr428** [LiveFastEatTrashRaccoon/RaccoonForFriendica#264]
Hi alls;
first off, chapeau, given the early stage of development, Racoon's already quite a mature and powerful tool. Great work. Looking forward to see this grow. Minor feature request for now: I usually try to hide random replies that don't mention me from my timelines. Can you by chance add this as an option?
Thanks!

**Comment by AkesiSeli** [comment]
Yes, I was actually thinking about adding a "Exclude replies in main feeds" in order to avoid having replies in the subscriptions/all/local timelines because it bothers me too to have all those replies.

Unfortunately, it's a filtering I'll have to do client-side so it may not be super efficient but considering I'll default it to `false` only few users will actually activate the filter.
