### ISSUE TITLE
[Timeline] Crash when scrolling

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#599]
**Describe the bug**
When I scroll through the posts, the app crashes.

**Smartphone (please complete the following information):**
 - Device: Pixel2XL
 - OS: Android 14
 - Version 0.3.1
com.livefast.eattrash.raccoonforfriendica

**Comment by AkesiSeli** [comment]
I've seen some reports about crashed in the timeline due to duplicated post IDs. I have client-side deduplication logic but apparently sometimes it is not working. (I never managed to reproduce it 😭)

**Question**: does it happen on all "timeline types" (_Local_, _Subscriptions_, _All_, circle, channel, group) or just in some of them?

This piece of information is crucial because they correspond to different API calls and are handled differently in the app.

**Comment by AkesiSeli** [comment]
Nevermind I think I found it on my own.
